from app.core.rules.categories import Category

KEYWORD_RULES = {
    Category.JOB: {
        "interview": 20,
        "internship": 20,
        "hiring": 20,
        "career": 15,
        "resume": 15,
        "candidate": 15,
        "job": 15,
        "offer": 20,
        "assessment": 20,
        "application": 15,
        "recruiter": 20,
    },
    Category.TECH: {
        "python": 10,
        "fastapi": 12,
        "postgres": 10,
        "redis": 10,
        "docker": 10,
        "llm": 15,
        "machine learning": 15,
        "deep learning": 15,
        "tutorial": 12,
        "guide": 10,
        "blog": 10,
        "newsletter": 10,
    },
    Category.SOFTWARE: {
        "api": 12,
        "sdk": 12,
        "deployment": 15,
        "docker": 12,
        "kubernetes": 15,
        "postgres": 12,
        "redis": 12,
        "cloud": 12,
        "gcp": 15,
        "aws": 15,
        "azure": 15,
        "billing": 10,
        "invoice": 8,
        "subscription": 8,
        "credits": 10,
        "firebase": 15,
        "gemini": 15,
        "vertex": 15,
        "render": 15,
        "supabase": 15,
        "vercel": 15,
    },
    Category.BANK: {
        "account": 20,
        "statement": 25,
        "transaction": 25,
        "credited": 25,
        "debited": 25,
        "balance": 20,
        "upi": 20,
        "bank": 20,
        "loan": 15,
        "emi": 15,
        "payment": 12,
        "interest": 12,
    },
}
